version: '3'

services:
  app:
    container_name: mirumon-backend
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    container_name: mirumon-db
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
  redis:
    container_name: mirumon-redis
    image: redis:5.0-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    env_file:
      - .env
