version: '3'

services:
  app:
    container_name: mirumon-backend:dev
    build:
      context: .
#      cache_from:
#        - mirumon-backend:dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      APP_ENV: dev
    depends_on:
      - postgres
      - redis
  postgres:
    container_name: mirumon-postgres
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
  redis:
    container_name: mirumon-redis
    image: redis:5.0-alpine
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"

